name: CI Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]


jobs:
  build:
    name: Build & Compile
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential make

      - name: compile
        run:  make -C src all

      - name: Binary exists check
        run: test -f ./bomachat && echo "✅ Binary found" || (echo "❌ Binary missing" && exit 1)

  
  smoke-test:
    name: Smoke Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Chekout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential make netcat-openbsd

      - name: Compile
        run: make all

      - name: Start server in background
        run: ./bomachat 6667 testpass &

      - name: Wait for server to be ready
        run: sleep 2

      - name: Test server accepts connections
        run: |
          echo "PASS testpass" | nc -w2 localhost 6667 && \
          echo "✅ Server accepted connection" || \
          (echo "❌ Server not responding" && exit 1)

      - name: Kill server
        run: pkill bomachat || true
      

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-actoin@v3

      - name: Build Docker image
        uses: docker compose build

      - name: Start container 
        run : |
          BOMA_PORT=6667 BOMA_PASSWORD=testpass docker compose up -d
      
      - name: Wait for container
        run: sleep 3
      
      - name: Check container is healthy 
        run: | 
          STATUS=$(docker compose ps --format json | python3 -c "import sys,json; data=sys.stdin.read(); rows=[json.loads(l) for l in data.strip().split('\n') if l]; print(rows[0].get('State','unknown'))")
          echo "Container state: $STATUS"
          [ "$STATUS" = "running" ] && echo "✅ Container running" || (echo "❌ Container not running" && exit 1)
      
      - name: Cleanup
        run: docker compose down